site_name: Documentación de Grader
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      primary: blue
      accent: purple
  font:
    text: Roboto


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'Inicio': 'index.md'
  - 'Arquitectura': 'arquitectura.md'
  - 'Desarrollo':
    - 'Prerrequisitos': 'developing/prerequisites.md'
    - 'Setup': 'developing/setup.md'
    - 'Running': 'developing/running.md'
    - 'Debugging': 'developing/debugging.md'
    - 'Testing':
      - 'Overview': 'testing/overview.md'
      - 'Prerrequisitos': 'testing/prerequisites.md'
      - 'Running': 'testing/running.md'
    - 'Releasing': 'releasing/overview.md'
  - 'Contribuir':
    - 'Owner': 'owner.md'
    - 'Contributing': 'contributing.md'
    - 'Guía de contribución': 'contributing/how-to.md'
  - 'Legal':
    - 'Política de privacidad': 'legal/privacidad.md'
    - 'Licencia': 'legal/licencia.md'
